### ISSUE TITLE
Geomet does not support explicit M, Z, or ZM WKT

### ISSUE THREAD

**Issue by tomplex** [geomet/geomet#58]
```python
>>> from geomet import wkt
>>> wkt.loads('POINT M (0 0 5)')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    wkt.loads('POINT M (0 0 5)')
  File "/private/tmp/v/lib/python3.6/site-packages/geomet/wkt.py", line 147, in loads
    result = importer(tokens, string)
  File "/private/tmp/v/lib/python3.6/site-packages/geomet/wkt.py", line 351, in _load_point
    raise ValueError(INVALID_WKT_FMT % string)
ValueError: Invalid WKT: `POINT M (0 0 5)`
```

We should allow parsing of WKT with extra dimensionality information.

**Comment by tagesk** [comment]
The Norwegian Road Authority offers all public roads in Norway as `{"wkt":` "MULTILINESTRING Z ((17125.6 6844496.8 55.343, 17119.6 6844492.2 55.643), (17085.6 6844528.1 55.443, 17090.6 6844534.3 55.443))"}`.

**Comment by Cameronsplaze** [comment]
As a temp fix, you can pull out the 3D tags, and the coords will still load correctly.
(Replace with space, to still keep 'POLYGON' separated from '(('.  )
```python
from geomet import wkt

str_wkt = "POLYGON Z ((0 0 0, 0 1 0, 1 1 0, 1 0 0, 0 0 0))"
json_wkt = wkt.loads(str_wkt) # Fails w/ same error as first post

str_wkt = str_wkt.replace(" Z ", " ").replace(" M ", " ").replace(" ZM ", " ")
json_wkt = wkt.loads(str_wkt) # Gives: {'type': 'Polygon', 'coordinates': [[[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0]]]}

```

**Comment by larsbutler** [comment]
I think there are two directions we can go with this:

1. Detect and drop any Z/M/ZM attribute from the WKT.
2. Detect any Z/M/ZM attribute, and then validate that the WKT has the correct number of dimensions for each point.

Approach 1 would be the simplest and least invasive. Approach 2 would be a bit more involved, since every parsed point would need to be validated. I think we can definitely start with the first approach, just to allow this valid WKT to be parsed, then we can consider additional validation features.

Thoughts?

**Comment by larsbutler** [comment]
Specification reference for Z/M/ZM WKT: https://www.ogc.org/standard/sfa/ -> https://portal.ogc.org/files/?artifact_id=25355 (PDF).

**Comment by larsbutler** [comment]
> Specification reference for Z/M/ZM WKT: https://www.ogc.org/standard/sfa/ -> https://portal.ogc.org/files/?artifact_id=25355 (PDF).

Another consideration, from page 52 of the linked spec:

```
The text representation of the instantiable Geometry Types implemented shall conform to this grammar. Well known text is case insensitive. Where human readability is important (as in the examples in this standard), an “upper camel-case” where each embedded word is capitalized, should be used.
```

The examples in https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry standardize on uppercase, which is the style we've been following. I think just to avoid too much thrashing, let's stick with all caps.
