### ISSUE TITLE
Conversion from EWKB does not support 3d

### ISSUE THREAD

**Issue by frisia-mtz** [geomet/geomet#89]
Hello,

I noticed when adding a column of type 'POINTZ' with SRID in PostGIS, that `geomet` cannot convert the type to GeoJSON.

See for example:

```sql
SELECT ST_GeomFromEWKT('SRID=4326;POINT Z(5 50 15)');
                          st_geomfromewkt
--------------------------------------------------------------------
 01010000A0E6100000000000000000144000000000000049400000000000002E40
```

```
from geomet import wkb
g = wkb.loads(bytes.fromhex('01010000A0E6100000000000000000144000000000000049400000000000002E40'))
Traceback (most recent call last):
  File "/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/.venv/lib/python3.9/site-packages/geomet/wkb.py", line 319, in loads
    _unsupported_geom_type(geom_type)
  File "/.venv/lib/python3.9/site-packages/geomet/wkb.py", line 335, in _unsupported_geom_type
    raise ValueError("Unsupported geometry type '%s'" % geom_type)
ValueError: Unsupported geometry type 'None'
```

`010000A0` is not found as a type and therefore throws an exception.

This was address in #31, but implemented tests in #32 only checked for 2d conversion.

**Comment by larsbutler** [comment]
@frisia-mtz Thanks for the bug report. I appreciate you taking the time to point this out and provide an example.

I think this is more of a general problem of the way the geometry type (bytes 1-5: `010000A0`) is represented in EWKB context. In EWKB, the `01` indicates a Point-type, and the `A0` is the bitwise OR [1] of an SRID flag (`0x20`) and a WKB Z offset (`0x80`) [2] --> `0x20 | 0x80 = 0xa`. `geomet` is checking for the presence of the SRID flag [3] but it's not expecting the dimensional offset.

It looks like the reverse of the conversion (`dumps`/to WKB) is also not correctly setting the dimensionality flag [4].

It looks like the correct fix would be to:
- look for the dimensionality flag when parsing EWKB
- inject the dimensionality flag when generating EWKB

@tomplex @achapkowski Would you both agree with this assessment? Is there anything I'm missing, perhaps an alternate EWKB spec independent of PostGIS that would contradict this and cause additional breakage in other use cases, if we were to fix this per the PostGIS spec?

References:
[1] - https://github.com/postgis/postgis/blob/b1b8c11bfe54d7756ed53719e74783dd2733d3df/doc/ZMSgeoms.txt#L56-L66
[2] - https://github.com/postgis/postgis/blob/b1b8c11bfe54d7756ed53719e74783dd2733d3df/liblwgeom/liblwgeom.h.in#L124-L127
[2] - https://github.com/geomet/geomet/blob/8d2b8f281ef7a919fa0cc9dd5230304d9ff71bd2/geomet/wkb.py#L135
[3] - https://github.com/geomet/geomet/blob/8d2b8f281ef7a919fa0cc9dd5230304d9ff71bd2/geomet/wkb.py#L336-L373

**Comment by gzt5142** [comment]
Hello, 

Curious the status of this bugfix and timeline.  
I'm encountering it also (I believe it's the same issue): 

```
data = b'\x01\x02\x00\x00`\xad\x10\x00\x00\x02\x00\x00\x00\x00\x00H\xc8\xc3WV\xc0\x00\x00\xc0,H\xa0E@\x00\x00\x00\x00\x00\x00Y@\x00\x00x\x06\x90WV\xc0\x00\x00\xb0\xa5X\xa0E@\x00\xc4\x86\xa7W\x9eV@'

geomet.wkb.loads(data)
## File ~/.venv/lib/python3.12/site-packages/geomet/wkb.py:316, in loads(string)
##    [313] importer = _loads_registry.get(geom_type)
##    [315] if importer is None:
##--> [316]     _unsupported_geom_type(geom_type)
##    [318] data_bytes = iter(data_bytes)
##    [319] result = importer(big_endian, type_bytes, data_bytes)
##
## File ~/.venv/lib/python3.12/site-packages/geomet/wkb.py:332, in _unsupported_geom_type(geom_type)
##    [331] def _unsupported_geom_type(geom_type):
## --> [332]     raise ValueError("Unsupported geometry type '%s'" % geom_type)
##
## ValueError: Unsupported geometry type 'None'

geom = shapely.wkb.loads(data)
geom.wkt
## 'LINESTRING M (-89.3713246062398 43.25220260024071 100, -89.36816560477018 43.25270529836416 90.47410000000673)'

shapely.get_srid(geom)
## np.int32(4269)
```

I'm really hoping not to require a `shapely` dependency in my project, given that its only use would be this wkb parsing. 

thanks so much,
